#echo cat.sh
#cat cat.sh
#echo CMakeLists.txt
#cat CMakeLists.txt
#echo GUI/CMakeLists.txt
#cat GUI/CMakeLists.txt
echo GUI/gui.c
cat GUI/gui.c
echo GUI/gui.h
cat GUI/gui.h
#echo lvgl/CMakeLists.txt
#cat lvgl/CMakeLists.txt
#echo lvgl/lv_port_stm32.c
#cat lvgl/lv_port_stm32.c
#echo lvgl/lvgl.h
#cat lvgl/lvgl.h
#echo lvgl/lv_port.h
#cat lvgl/lv_port.h
#echo lvgl/lv_conf.h
#cat lvgl/lv_conf.h
#echo platform/pc/CMakeLists.txt
#cat platform/pc/CMakeLists.txt
#echo platform/pc/main_pc.cpp
#cat platform/pc/main_pc.cpp
#echo platform/stm32/CMakeLists.txt
#cat platform/stm32/CMakeLists.txt
#echo platform/pc/lv_port_pc.c
#cat platform/pc/lv_port_pc.c
#echo platform/pc/lv_port_pc.h
#cat platform/pc/lv_port_pc.h
echo App/app.cpp
cat App/app.cpp
echo App/app.h
cat App/app.h

